### ISSUE TITLE
动态加载问题

### ISSUE THREAD

**Issue by magicdict** [worktile/ngx-gantt#152]
![image](https://user-images.githubusercontent.com/897796/135217838-5c1df084-3320-4761-b6ac-910bb0f37836.png)

这个甘特图是在某一个Tab中的，如果该Tab是一开始就显示的，则没有问题。
但是这个Tab在页面开始的时候是不显示，所以刚开始渲染的时候，可能ngfor什么都没有做。
等到这个Tab被现实的时候，则任务名称都无法显示了。
而且，这个高度我也是手工设置的，因为数据是动态加载的，所以他高度计算会有问题。

能不能增加一个 Refresh方法，强制刷新甘特图呢？
希望能告诉我一个解决方案。

**Comment by magicdict** [comment]
另一个问题：如果项目的颜色color进行了设置，则无法用颜色表示进度了（整体颜色都一样，无法区分）

![image](https://user-images.githubusercontent.com/897796/136643299-49595cae-cf0c-4cce-850d-4075fb3d209f.png)

**Comment by walkerkay** [comment]
> ![image](https://user-images.githubusercontent.com/897796/135217838-5c1df084-3320-4761-b6ac-910bb0f37836.png)
> 
> 这个甘特图是在某一个Tab中的，如果该Tab是一开始就显示的，则没有问题。 但是这个Tab在页面开始的时候是不显示，所以刚开始渲染的时候，可能ngfor什么都没有做。 等到这个Tab被现实的时候，则任务名称都无法显示了。 而且，这个高度我也是手工设置的，因为数据是动态加载的，所以他高度计算会有问题。
> 
> 能不能增加一个 Refresh方法，强制刷新甘特图呢？ 希望能告诉我一个解决方案。



> 另一个问题：如果项目的颜色进行了设置，则无法用颜色表示了（整体颜色都一样，无法分辨）
> 
> ![图片](https://user-images.githubusercontent.com/897796/136643299-49595cae-cf0c-4cce-850d-4075fb3d209f.png)

可否贴一个脱敏的Demo或者是你的代码片段？  数据变化后Gantt会自动刷新的，不需要主动Refresh

**Comment by walkerkay** [comment]
> 另一个问题：如果项目的颜色color进行了设置，则无法用颜色表示进度了（整体颜色都一样，无法区分）
> 
> ![image](https://user-images.githubusercontent.com/897796/136643299-49595cae-cf0c-4cce-850d-4075fb3d209f.png)

这是一个Bug，我们会在12.0.1版本修复它

**Comment by walkerkay** [comment]
> 另一个问题：如果项目的颜色color进行了设置，则无法用颜色表示进度了（整体颜色都一样，无法区分）
> 
> ![image](https://user-images.githubusercontent.com/897796/136643299-49595cae-cf0c-4cce-850d-4075fb3d209f.png)

我尝试了自定义颜色然后设置百分比是正常的
>   { id: '0000022', title: 'Task 22', start: 1616238797, end: 1620731597, color: '#90ee8f', progress: 0.5 }
![image](https://user-images.githubusercontent.com/15701592/140675431-9116a721-4c4d-4799-a78e-6e97fb992213.png)

**Comment by magicdict** [comment]
@walkerkay 颜色的话，如果是rbg的时候，的确没有问题，多谢。不过当color是 lightgreen 的时候则不行。

**Comment by walkerkay** [comment]
> @walkerkay 颜色的话，如果是rbg的时候，的确没有问题，多谢。不过当color是 lightgreen 的时候则不行。

是的，由于需要动态转换颜色，目前只支持RGB颜色值，不过后续我们将支持浏览器内置的140中颜色名称 #160
