### ISSUE TITLE
'ngx-gantt' is not a known element: 

### ISSUE THREAD

**Issue by bastifix** [worktile/ngx-gantt#162]
Hi, I'd love to use ngx-gantt!
I tried to implement it like in the docs, but unfortunately there is this error coming:

```
'ngx-gantt' is not a known element:
1. If 'ngx-gantt' is an Angular component, then verify that it is part of this module.
2. If 'ngx-gantt' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 
```

**Comment by HandsomeButterball** [comment]
> Hi, I'd love to use ngx-gantt! I tried to implement it like in the docs, but unfortunately there is this error coming:
> 
> ```
> 'ngx-gantt' is not a known element:
> 1. If 'ngx-gantt' is an Angular component, then verify that it is part of this module.
> 2. If 'ngx-gantt' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 
> ```

Check your code to confirm that you have added NgxGanttModule to your AppModule like this: 

import { NgModule } from '@angular/core';
import { NgxGanttModule } from '@worktile/gantt';

@NgModule({
  ...
  imports: [ NgxGanttModule, ... ]
  ...
})
export class AppModule {

}

**Comment by bastifix** [comment]
For sure, I added this ;-)
