### ISSUE TITLE
Using time resolution along with day, month, year

### ISSUE THREAD

**Issue by srijeyanthan-cx** [worktile/ngx-gantt#176]
How can we change the view format to time showing 24 hours, looks like that view is not supported, can you give some hint on changing the core?

**Comment by walkerkay** [comment]
> How can we change the view format to time showing 24 hours, looks like that view is not supported, can you give some hint on changing the core?

Hello, srijeyanthan-cerexio, at present, we have no plan to support hourly view. If you are interested, you can submit PR for support, the core code of ngx-gantt view is located in 'packages/gantt/src/ views'.  You can add a' hour.ts ` extends GanttView 'to implement a new view. There may be new problems in the implementation process. You can use walkerkay@163.com Email to communicate with me.

**Comment by mhosman** [comment]
It would be great to have a 24 hour view.

**Comment by maleet** [comment]
Almost doable with custom day view. But there is core logic there and that makes my date with time to date so I can't calculate bar width.

In this way it works:

gantt-upper.ts:
computeItemsRefs(...items: GanttItemInternal[] | GanttBaselineItemInternal[]) {
        items.forEach((item) => {
            item.updateRefs({
                width: item.start && item.end ? this.view.getDateRangeWidth(item.start, item.end) : 0,
                x: item.start ? this.view.getXPointByDate(item.start) : 0,
                y: (this.styles.lineHeight - this.styles.barHeight) / 2 - 1
            });
        });
    }
