### ISSUE TITLE
Adjusting width in firefox is jank

### ISSUE THREAD

**Issue by MrHeer** [worktile/ngx-gantt#200]
Please see the demo
![2022-03-15 15 17 57](https://user-images.githubusercontent.com/18595761/158326133-4e60fb7f-9151-4257-90a0-9fd9c40eb4b1.gif)

**Comment by walkerkay** [comment]
We have reproduced this problem and will fix it as soon as possible

**Comment by walkerkay** [comment]
Fixed in `ngx-gantt@13.0.0` version. @MrHeer
