### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by weilinzung** [worktile/ngx-gantt#222]
It would be great that the doc could has English version: http://gantt.ngnice.com/guides/intro

**Comment by HandsomeButterball** [comment]
> It would be great that the doc could has English version: http://gantt.ngnice.com/guides/intro


We are also planning this and we will support it as soon as possible.

**Comment by hauserkristof** [comment]
Dear @HandsomeButterball indeed an English version of the documentation would be nice.

Thank you for the amazing project!

**Comment by ly000** [comment]
Any update on the english doc?

**Comment by kishoreinvits** [comment]
Thanks for creating this great project!

For anyone waiting for English documentation, but cannot contribute to this opensource project, feel free to use translate feature in chrome/edge to see it in English or whatever language you want to see.
