### ISSUE TITLE
如果进度组件延迟展示，则初始化的时间轴位置不正确

### ISSUE THREAD

**Issue by magicdict** [worktile/ngx-gantt#223]
如果进度组件在TabView里面，但是并不在第一个Tab里面，则时间轴初始化表示的位置在最前面
![image](https://user-images.githubusercontent.com/897796/166883080-32def107-35f8-43bf-837e-b8121853996a.png)
如果是在Tab的默认第一个位置，中心位置是今天
![image](https://user-images.githubusercontent.com/897796/166883140-d00425fa-7daa-4c3f-b4e6-4713febc2869.png)

另外更特图的时间范围能不能自己定义一下，现在默认好像是前后总共一年时间，有的小项目来说，太长了。还有就是中心位置是否也能配置呢？

**Comment by HandsomeButterball** [comment]
> 如果进度组件在TabView里面，但是并不在第一个Tab里面，则时间轴初始化表示的位置在最前面 ![image](https://user-images.githubusercontent.com/897796/166883080-32def107-35f8-43bf-837e-b8121853996a.png) 如果是在Tab的默认第一个位置，中心位置是今天 ![image](https://user-images.githubusercontent.com/897796/166883140-d00425fa-7daa-4c3f-b4e6-4713febc2869.png)
> 
> 另外更特图的时间范围能不能自己定义一下，现在默认好像是前后总共一年时间，有的小项目来说，太长了。还有就是中心位置是否也能配置呢？

你们的延迟加载是怎么实现的，有去动态更新传入的数据么，方便的话能贴下代码么？另外，我们支持自定义时间范围的，需要传入`start`和`end`参数，文档里有的，中心位置默认就是今天，暂不支持配置的

**Comment by walkerkay** [comment]
Issue has not been active for a long time, closed
