### ISSUE TITLE
Angular 13 support?

### ISSUE THREAD

**Issue by fijas** [worktile/ngx-gantt#225]
Very cool library. Any plans to update to Angular 13?

**Comment by HandsomeButterball** [comment]
> Very cool library. Any plans to update to Angular 13?
We are upgrading Angular 13 and will release a new version this week.

**Comment by walkerkay** [comment]
> I got the v13.next preview running in a new ng 13.3.0 app but needed to run install the following deps:
> 
> ```
> npm i @worktile/gantt html2canvas @angular/cdk date-fns
> ```

yes, ngx-gantt dependent these
![image](https://user-images.githubusercontent.com/15701592/169243735-3c1e692d-7806-4776-84b5-608022ec275c.png)

**Comment by walkerkay** [comment]
`13.0.0-next.1 ` Published
