### ISSUE TITLE
是否可以增加时间线数据类型，或者说有什么方法可以让我多加几根时间线？

### ISSUE THREAD

**Issue by 2863416607** [worktile/ngx-gantt#226]

**Comment by 2863416607** [comment]
![1652691766179_347EF64E-B4F8-4cf2-985A-7CB1F14EAE47](https://user-images.githubusercontent.com/44248814/168557834-8babda72-01f8-4e07-8143-29e29a1c4e7f.png)

**Comment by 2863416607** [comment]
![1652691766179_347EF64E-B4F8-4cf2-985A-7CB1F14EAE47](https://user-images.githubusercontent.com/44248814/168557968-099abfe7-9692-4f54-97d6-e36ebda9bd62.png)
类似于这种效果

**Comment by lsymy** [comment]
Hi，请问你实现了吗？ 我也在寻找这个需求的解决方案。

**Comment by lsymy** [comment]
已解决。
简单示例:
```
calendar-grid.component.html:
<div class="gantt-calendar-today-overlay" [style.width.px]="view.width">
  <span class="today-line" *ngIf="ganttUpper.showTodayLine"> </span>
</div>

<div class="gantt-calendar-custom-overlay" [style.width.px]="view.width">
  <span class="custom-line"> </span>
</div>
```

![image](https://github.com/worktile/ngx-gantt/assets/48469171/141088fd-a705-40f9-b9f7-2d3ffdeae8ed)
