### ISSUE TITLE
如果不设置[disabledLoadOnScroll]="ture"，左右拖动滚动条后，出现很多空白，bar也会消失一段时间，过一会可能会出现

### ISSUE THREAD

**Issue by naruto00fa** [worktile/ngx-gantt#230]
如果不设置[disabledLoadOnScroll]="ture"，左右拖动滚动条后，出现很多空白，bar也会消失一段时间，过一会可能会出现

**Comment by walkerkay** [comment]
> 如果不设置[disabledLoadOnScroll]="ture"，左右拖动滚动条后，出现很多空白，bar也会消失一段时间，过一会可能会出现

我没有复现出来你的问题，可以贴一个最小化的Demo或者更详细的描述你遇到的问题吗？

**Comment by naruto00fa** [comment]
我发现就是我的数据比较多，共137个ganttItems和7个ganttGroups，ganttItems又做了嵌套关系，所以自动扩展横向滚动条画图比较慢。
