### ISSUE TITLE
建议：实现mergedItems功能

### ISSUE THREAD

**Issue by naruto00fa** [worktile/ngx-gantt#239]
我看group.ts源码里已经有了mergedItems属性，Item也可以支持此功能，实现打平展示。

**Comment by walkerkay** [comment]
可以参考高级使用的Demo，通过组件提供的基础功能来实现  http://gantt.ngnice.com/components/advanced

**Comment by naruto00fa** [comment]
此demo

**Comment by naruto00fa** [comment]
此demo只支持一级的打平展示，并且屏蔽了其他功能，所以不太符合需求
