### ISSUE TITLE
组件的height，top，left等样式，是否可以放入class中便于扩展？

### ISSUE THREAD

**Issue by naruto00fa** [worktile/ngx-gantt#240]
如图，除了width之外的样式，是否可以放入class中便于扩展？
![image](https://user-images.githubusercontent.com/23647708/169941899-f6c3e4c2-8338-404a-91a7-561b6ce8f6df.png)

**Comment by walkerkay** [comment]
top left是动态计算的，不可以放在class中， height 可以通过 `styles="{lineHeight:50}"` 参数来设置

**Comment by naruto00fa** [comment]
谢谢
