### ISSUE TITLE
Error trying to print

### ISSUE THREAD

**Issue by alopezo** [worktile/ngx-gantt#243]
I get this error, apparently the clonedDom is undefined:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/4990842/171665850-584349a1-07b1-4867-bbf2-b1914d50d692.png">
<img width="810" alt="image" src="https://user-images.githubusercontent.com/4990842/171666018-b10f4ddf-c0e2-4270-8627-869e19dd9960.png">

Am I missing something? The Gantt is properly displayed on an angular dialog...

Thanks

**Comment by walkerkay** [comment]
Could you tell me how you use it?  I'll try to reproduce him.

**Comment by alopezo** [comment]
Of course, this is the chart component:

<ngx-gantt #gantt [start]="roadmapStart" [end]="roadmapEnd" [items]="ganttData">
    <ngx-gantt-table>
        <ngx-gantt-column name="Title" width="20px">
        <ng-template #cell let-item="item"> {{ item.title }} </ng-template>
        </ngx-gantt-column>
    </ngx-gantt-table>
</ngx-gantt>
<button mat-flat-button color="primary" (click)="print('gantt-roadmap')">Print</button>

And it is used from a dialog:
<h1 mat-dialog-title>{{data.country}}: SNOMED CT Implementation Roadmap</h1>
<div mat-dialog-content>
  <div>
    <app-gantt-chart [roadmapStart]="data.roadmapStart" [roadmapEnd]="data.roadmapEnd" [selectedSteps]="data.selectedSteps"></app-gantt-chart>
  </div>
</div>
<div mat-dialog-actions>
  <button mat-flat-button [mat-dialog-close]="data" cdkFocusInitial>Close</button>
</div>

Do you need any other details?

Thanks!

**Comment by HandsomeButterball** [comment]
> Of course, this is the chart component:
> 
> <img alt="image" width="707" src="https://user-images.githubusercontent.com/4990842/172146212-f17cda43-9b13-403f-936f-8bd678bb7ce8.png">
> 
> And it is used from a dialog:
> 
> <img alt="image" width="1048" src="https://user-images.githubusercontent.com/4990842/172146245-0b20185d-f1f4-4245-96d9-ce71796ae909.png">
> 
> Do you need any other details?
> 
> Thanks!

Try to use fixed version of html2canvas
```ts
"html2canvas": "1.0.0-rc.7",
```
