### ISSUE TITLE
Re-rendering chart options

### ISSUE THREAD

**Issue by dr34w** [worktile/ngx-gantt#244]
Hi, I'm facing the issue when I need to change the end date of the chart in the viewOptions, but the chart options config is not applied.
Is there any way to re-render the chart on a fly with a new endDate in the viewOptions?

**Comment by naruto00fa** [comment]
Same as my problem at #237 .

I use this tric, by resetint the cycle, which is your month, week or something:

```
     private _sendGanttRangeChange(){
        let temp = this.cycleSelected;
        this.cycleSelected = '';
        setTimeout(()=>{
        this.cycleSelected = temp;
        },100);
    }
```

As walkerkay say, can also use:
`this.items=[...this.items];`

**Comment by walkerkay** [comment]
```
 @ViewChild('gantt') ganttComponent: NgxGanttComponent;

 this.ganttComponent.rerenderView();
```
