### ISSUE TITLE
安装后出现问题

### ISSUE THREAD

**Issue by shixin96** [worktile/ngx-gantt#257]
使用npm i @worktile/gantt html2canvas --save安装后，启动出现错误。这是什么原因导致的
`./node_modules/@worktile/gantt/fesm2020/worktile-gantt.mjs:5163:33-44 - Error: export 'takeUntil' (imported as 'takeUntil$1') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)`

**Comment by Moicechul** [comment]
请问这个问题解决了吗
