### ISSUE TITLE
按照小时来设计甘特图

### ISSUE THREAD

**Issue by angela-abcd** [worktile/ngx-gantt#264]
GanttViewType 会考虑增加小时么？
`export declare enum GanttViewType {
    day = "day",
    quarter = "quarter",
    month = "month",
    year = "year",
    week = "week"
}`

**Comment by walkerkay** [comment]
> GanttViewType 会考虑增加小时么？ `export declare enum GanttViewType { day = "day", quarter = "quarter", month = "month", year = "year", week = "week" }`

是的会支持，目前有一个PR就是在处理这个事情，不过小时视图会带来一些新的问题，目前正在解决中
