### ISSUE TITLE
Sorting left pane with header

### ISSUE THREAD

**Issue by RiderOfTheli** [worktile/ngx-gantt#267]
Is it possible to use sorting (like in a standard table) to sort / filter rows in the left pane of gantt?

**Comment by HandsomeButterball** [comment]
> Is it possible to use sorting (like in a standard table) to sort / filter rows in the left pane of gantt?

We currently have no plans to support this feature in ngx-gantt，but you can achieve this requirement through custom template

```html
<ngx-gantt>
  <ngx-gantt-table>
    <ngx-gantt-column>
      <ng-template #header>
        <div class="sort-icon" (click)="sort()"></div>
      <ng-template/>
      <ng-template #cell let-row>
        ...
      <ng-template/>
    </ngx-gantt-column>
  </ngx-gantt-table>
</ngx-gantt>
```
