### ISSUE TITLE
Bar tooltip

### ISSUE THREAD

**Issue by RiderOfTheli** [worktile/ngx-gantt#268]
Is it possible to create a bar tooltip that will show selected parts from the left pane - like start date, end date, title etc?

Thank you!

**Comment by HandsomeButterball** [comment]
> Is it possible to create a bar tooltip that will show selected parts from the left pane - like start date, end date, title etc?
> 
> Thank you!

You can open a bar tooltip by `barClick` 
```html
<ngx-gantt #gantt [items]="items" (barClick)="barClick($event)">
</ngx-gantt>
```

```javascript
barClick(event: GanttBarClickEvent) {
    this.dialog.open();
}
```

If you wan to open a bar tooltip by hover, you can use template
```html
<ngx-gantt #gantt [items]="items">
  <ng-template #bar let-item="item">
    <div> you can open tooltip here</div>
  </ng-template>
</ngx-gantt>
```
