### ISSUE TITLE
private scrollToToday; 能否把旧版本的"@worktile/gantt": "^11.0.3", ngx-root-> scrollToToday() 方法改为public

### ISSUE THREAD

**Issue by RokeyJoe** [worktile/ngx-gantt#269]
尊敬的博主, 您好, 我们在客制化gantt 图的时候, 想要调用ngx-root的方法, 快速定位回当前日期, 但是发现我们angular版本对应的package该方法(**scrollToToday**())类型为private, 没办法使用, 不知道您这边能否将旧版本的方法类型改为public, 十分感谢您百忙之中查看此请求, 期待您的回复~

**Comment by HandsomeButterball** [comment]
> 尊敬的博主, 您好, 我们在客制化gantt 图的时候, 想要调用ngx-root的方法, 快速定位回当前日期, 但是发现我们angular版本对应的package该方法(**scrollToToday**())类型为private, 没办法使用, 不知道您这边能否将旧版本的方法类型改为public, 十分感谢您百忙之中查看此请求, 期待您的回复~

你们是出于什么原因不能升级呢，我们不太想向下兼容

**Comment by walkerkay** [comment]
使用 gantt['scrollToToday']() 是否可以解决你的问题
