### ISSUE TITLE
Translation Engish

### ISSUE THREAD

**Issue by Razgort** [worktile/ngx-gantt#270]
Hello guys,
Sorry to bother you here, is there a translation in english of your website demo with the gantt planning that i see here ?
http://gantt.ngnice.com/components/basic

Thanks in advance, 
And congrats for your work

**Comment by HandsomeButterball** [comment]
> Hello guys, Sorry to bother you here, is there a translation in english of your website demo with the gantt planning that i see here ? http://gantt.ngnice.com/components/basic
> 
> Thanks in advance, And congrats for your work

There is already the same issuse below, we will support it as soon as possible.
https://github.com/worktile/ngx-gantt/issues/222
