### ISSUE TITLE
Error in nested children

### ISSUE THREAD

**Issue by Braulio-F** [worktile/ngx-gantt#304]
When we create a Gantt Item with more than 2 levels, the component didnt work as expected, the children of the children cant load correctly, here is an example to replicate this issue : 

### TS Component 

`items: GanttItem[] = [ `
`    { `
`      id: '000000', `
`      title: 'Task 0', `
`      start: 1627729997, `
`      end: 1628421197, `
`      expandable: true, `
`      children: [ `
`        { `
`          id: '000002', `
`          title: 'Task 2', `
`          start: 1627729997, `
`          end: 1628421197, `
`          expandable: true, `
`          expanded: true, `
`          children: [ `
`            { `
`              id: '000003', `
`              title: 'Task 3', `
`              start: 1627729997, `
`              end: 1628421197, `
`            }, `
`            { `
`              id: '000004', `
`              title: 'Task 4', `
`              start: 1627729997, `
`              end: 1628421197, `
`            }, `
`          ], `
`        }, `
`        { id: '000005', title: 'Task 5', start: 1627729997, end: 1628421197 }, `
`      ], `
`    }, `
`    { id: '000006', title: 'Task 6', start: 1627729997, end: 1628421197 }, `
`  ]; `

### HTML Component

`<ngx-gantt #gantt [items]="items" [maxLevel]="10"> `
`  <ngx-gantt-table>`
`    <ngx-gantt-column name="Title" width="300px">`
`      <ng-template #cell let-item="item"> {{ item.title }} </ng-template>`
`    </ngx-gantt-column>`
`  </ngx-gantt-table>`
`</ngx-gantt>`

### Result

As you can see in the image all the items have the same dates but for the items 3 and 4 we can see the timeline just for this items even when the max-level attribute has a value of 10 

![image](https://user-images.githubusercontent.com/123000395/217617873-e333b6c0-e18c-450f-8b03-9116bef631e9.png)

if it's something that im not doing correctly please let me know, it's kinda hard read the documentation since im not Chinese speaker

**Comment by wajipk** [comment]
[maxLevel]="10"
 
 Remove [] brackets. [] brackets means you are passing variable.
