### ISSUE TITLE
How to update gantt with new data?

### ISSUE THREAD

**Issue by hazaart** [worktile/ngx-gantt#320]
I want to update the data in the gantt based on an API call to fetch the data.
The documentation is only covering static data.
How can I rerender the gantt with the new items after the data is fetched?
By changing the 'items' array, nothing happens.

**Comment by Bykiev** [comment]
same here, as a workaround you can use `ngIf` to redraw the component

**Comment by walkerkay** [comment]
The solution is the same as  #244 #237
