### ISSUE TITLE
Expand & collapse arrows are not visible for childrens

### ISSUE THREAD

**Issue by muleakshay29** [worktile/ngx-gantt#339]
Is it possible to show Expand & collapse arrows for children as well?
I have data with nested children structure. The expand and collapse arrow showing only for parent element.

![image](https://user-images.githubusercontent.com/13780594/227920570-d3df86bb-23ad-451a-a79e-f45a8a1ac152.png)

Can you please help here?

**Comment by walkerkay** [comment]
There are two parameters that control the display of hierarchical arrows:

"maxLevel" is set to 2 by default, but you can set it to a larger value.
You need to set "expandable" to true in your data (this may not be the best practice, so it has been improved in version 15.1.0-next, where the expand icon is automatically displayed when there are children data).
