### ISSUE TITLE
can't resolve 'ngx-tethys/core' in v15.1.0

### ISSUE THREAD

**Issue by hizikata** [worktile/ngx-gantt#372]
version：v15.1.0
![image](https://github.com/worktile/ngx-gantt/assets/35916025/f49c6ba9-2aae-4f67-bce7-da33ffed9c07)

**Comment by FossaMalaEnt** [comment]
Same

**Comment by walkerkay** [comment]
upgrade "@worktile/gantt": "15.1.1"
