### ISSUE TITLE
Hour view - question

### ISSUE THREAD

**Issue by adamb92** [worktile/ngx-gantt#375]
Will be there hour view so I would be able to zoom graphs to hours? I am interested not only in zooming but making task for hour for example too. Do you think it is plenty of work to make it ?

**Comment by RicardoVaranda** [comment]
@walkerkay Any chance of adding an example on how we can go about doing this? There are several other issues raised about this since the start of the year. A simple demo on how this could be done would highly increase the chances of people using your package.

**Comment by walkerkay** [comment]
@worktile/gantt@17.0.0-next.0 supports hour view.
