### ISSUE TITLE
Display multiple tasks on same row

### ISSUE THREAD

**Issue by Bykiev** [worktile/ngx-gantt#378]
Hi, I'm new to this component, I need to display multiple tasks on same row e.g. one item from 2023-01-01 till 2023-02-21 and another one from 2023-03-22 till 2023-04-08. Is it possible with this component?

**Comment by uchitha** [comment]
Hi @Bykiev @walkerkay Can you pls provide me an example of how to get this to work? I have set [multiple]=true in the gantt. And my 2 items looks like this. I want these 2 items to appear on the same row of the Gantt. Thank you so much.

 ```
{ id: '000000', title: 'Task 0', start: 1627729997, end: 1627769997, linkable: false },
{ id: '000000', title: 'Task 0', start: 1624705997, end: 1625483597, linkable: false },

```
