### ISSUE TITLE
Allow user to change cell width

### ISSUE THREAD

**Issue by Bykiev** [worktile/ngx-gantt#383]
Hi, it'll be useful if users can resize gantt cell width

**Comment by walkerkay** [comment]
table cell resize ?  example includes cell width adjustment.
![image](https://github.com/worktile/ngx-gantt/assets/15701592/b579a1a9-2e03-461c-bc96-a02e86ea705e)

**Comment by Bykiev** [comment]
Hi, no, gantt cells resizing, similar to table

**Comment by walkerkay** [comment]
The width of each column cell in the calendar must be consistent, as inconsistency can lead to inaccurate bar calculations
