### ISSUE TITLE
Advanced Use Linking Gantt Items

### ISSUE THREAD

**Issue by barnacleDevelopments** [worktile/ngx-gantt#402]
I'm currently using a [Advanced Use Gantt Chart setup](http://gantt.ngnice.com/components/advanced) and I have added links to connect the gantt items together, but the items don't have the curved line connecting them. I noticed in the documentation the demo showing the advanced setup has gantt items with links but the demo does not display them as linked. Is it possible to have the curved line display itself in the advanced setup or will that be something I would need to implement myself?

Version: ^14.0.5

**Comment by walkerkay** [comment]
We do not provide links support for advanced usage, and you will need to implement these tasks yourself
