### ISSUE TITLE
ngx-gantt依赖ngx-tethys组件库吗

### ISSUE THREAD

**Issue by lsymy** [worktile/ngx-gantt#421]
左侧表格的表头在没有引入ngx-tethys的情况下 d-flex 缺少 display: flex，见p1 p2的d-flex类样式对比

p1:
![uTools_1695778025923](https://github.com/worktile/ngx-gantt/assets/48469171/58944fa9-f3c0-4088-a00b-6c27a8378f6e)

p2:
![uTools_1695778071924](https://github.com/worktile/ngx-gantt/assets/48469171/d4f6b5e2-9132-4313-bd76-5d4aeb98a5f0)

**Comment by HandsomeButterball** [comment]
不依赖，16.0.2 版本已修复
