### ISSUE TITLE
Multilanguage support for ngx-gantt-toolbar

### ISSUE THREAD

**Issue by bvzasfb** [worktile/ngx-gantt#426]
I think there should be the possibility to easily **customize the names of the the ganttViews used by ngx-gantt-toolbar.**

**Comment by walkerkay** [comment]
Yes, the built-in toolbar currently does not support i18n. We will improve it in the future, and now you can use # toolbar to customize the toolbar
```
    <ngx-gantt #gantt [items]="items">
        <ng-template #toolbar>
            <span class="custom-toolbar"></span>
        </ng-template>
    </ngx-gantt>
```
