### ISSUE TITLE
Row height

### ISSUE THREAD

**Issue by archie-arrow** [worktile/ngx-gantt#431]
I tried to override the default styles for row height as in docs:

```scss
@use '@worktile/gantt/styles/variables.scss' with (
  $gantt-item-height: 44px
)
```

But it doesn't affect the chart at all.
It's impossible to override it manually also because the SVG link lines are rendered at the wrong place.

**Comment by walkerkay** [comment]
I confirm that this is a defect，we will provide row height config in version 17

**Comment by walkerkay** [comment]
Please upgrade the version to resolve the issue
