### ISSUE TITLE
Cannot find name 'Locale' - error TS2304

### ISSUE THREAD

**Issue by HuntosShuntos** [worktile/ngx-gantt#436]
Hi, 

Getting the following error after installing the Package:

node_modules/@worktile/gantt/utils/date.d.ts:16:18 - error TS2304: Cannot find name 'Locale'.
(The error code occurs another few times on the file at : [date.d.ts:35:18, date.d.ts:43:18, date.d.ts:51:18])

I have tried searching through the repo but can't find use of 'locale' to try and resolve it. 

Any assistance on this would be fantastic.

Thanks

**Comment by HuntosShuntos** [comment]
Hi, 

I have resolved this now by doing the following.

Add the below code to the @worktile/gantt/utils/date.d.ts file:

`import { Locale } from `'date-fns';`

This resolved the issue, but have I missed something or is there a reason this isn't in the file?

Thanks!

**Comment by yanover** [comment]
I also encountered this error with Angular 17.

As a workaround, you can disabled lib check in your `tsconfig.json`
  "compilerOptions": {
    ...
    "skipLibCheck": true,
  },

**Comment by ri0t** [comment]
The mentioned workarounds do not work here. I'm on angular 16.0.0 and used ngx-gantt@16.0.3

**Comment by walkerkay** [comment]
fixed at 17.0.0-next.0 version

**Comment by EmadR** [comment]
There is still this problem on version 17.0.0-next.0 and it can be solved by adding "skipLibCheck": true to compilerOptions.
