### ISSUE TITLE
默认demo  月份视图切换到 周视图 无法切到今天

### ISSUE THREAD

**Issue by calibura** [worktile/ngx-gantt#437]
你好，在线demo中可以重现。
发现  root.component.ts 中 ngOnInit 里用了 scrollToToday 但是没生效，尝试添加 timeout 后可以实现定位到今天，但是会·闪一下，请问有更好的方式解决吗？
![image](https://github.com/worktile/ngx-gantt/assets/37359349/03102cc0-6241-44d3-b3b2-8b7b72810b45)

**Comment by walkerkay** [comment]
我测试 Demo 可以正常的滚动到今天，请提供更多的信息让我来排查

**Comment by walkerkay** [comment]
切换视图并不会重新渲染组件，所以不会重新执行 ngOnInit 中的 scrollToToday(), 如果有需要可以手动调用 scrollToday() 来实现
```
 @ViewChild('gantt') ganttComponent: NgxGanttComponent;

 this.ganttComponent.scrollToToday();
```
