### ISSUE TITLE
global scss interfere with angular material styles

### ISSUE THREAD

**Issue by deniskkk** [worktile/ngx-gantt#439]
angular: 16
angular-material: 16
gng-gantt: 16.0.3

.cdk-drag .cdk-drag-handle {
    visibility: hidden;
    padding: 0 15px 0 3px;
}

this styles in drag-drop.scss interfere with angular material styling. why are they global? Is there a way to fix this? do we have any workarounds?

**Comment by walkerkay** [comment]
fixed on 17.0.0-next.0
