### ISSUE TITLE
Hide table footer based on view type

### ISSUE THREAD

**Issue by Bykiev** [worktile/ngx-gantt#460]
Hi, I need to show/hide table footer based on view type. I've tried with this code and it doesn't working:

```
<ngx-gantt-table>
    <ngx-gantt-column name="标题" width="180px">
      <ng-template #cell let-item="item"> {{ item.title }} </ng-template>
    </ngx-gantt-column>
      <ng-template #tableFooter [ngIf]="gantt?.viewType == 'day'">
        <div class="stat stat-fill">test</div>
      </ng-template>
  </ngx-gantt-table>
```

v 15.2

**Comment by walkerkay** [comment]
> Hi, I need to show/hide table footer based on view type. I've tried with this code and it doesn't working:
> 
> ```
> <ngx-gantt-table>
>     <ngx-gantt-column name="标题" width="180px">
>       <ng-template #cell let-item="item"> {{ item.title }} </ng-template>
>     </ngx-gantt-column>
>       <ng-template #tableFooter [ngIf]="gantt?.viewType == 'day'">
>         <div class="stat stat-fill">test</div>
>       </ng-template>
>   </ngx-gantt-table>
> ```
> 
> v 15.2

Angular templates are not slots, so they do not support dynamic conditional if. Let me give you an idea to add different view classes when switching views, and then hide them through the class
