### ISSUE TITLE
Error using printService

### ISSUE THREAD

**Issue by Dqqstuday** [worktile/ngx-gantt#463]
Error using printService   The style has been imported correctly
![4688da123bdab071ecc548f808bdb660](https://github.com/worktile/ngx-gantt/assets/94945520/6ef9620f-46bb-4ea8-a568-6c3c12b22d23)

**Comment by Bykiev** [comment]
Hi, what version of `html2canvas` do you have installed?

**Comment by Dqqstuday** [comment]
"html2canvas": "^1.4.1",

**Comment by Bykiev** [comment]
Try "html2canvas": "1.0.0-rc.7"

**Comment by Dqqstuday** [comment]
Okay, the problem has been resolved, thank you.
