### ISSUE TITLE
Cannot show child tasks in multi level tree structure

### ISSUE THREAD

**Issue by Jahid1999** [worktile/ngx-gantt#468]
I am trying to display a tree structure, but the Gantt chart only shows first-level children. My tree data has three to four levels. Is it possible to display a multi-level tree structure?
***
##### Data Structure:
```
->A
    ---->B
          ---->BA
          ---->BB
    ---->C
->D
->E
    --->F
```

I cannot see `BA` and `BB` node in the gantt display.

**Comment by lsymy** [comment]
try this
```
<ngx-gantt [maxLevel]="urmaxlevel"></ngx-gantt>
```

**Comment by Oieusouopi** [comment]
Does version 12.2.3 already have this change?

**Comment by Oieusouopi** [comment]
Does version 12.2.3 already have this change?
