### ISSUE TITLE
"Today" line in hour view wrong

### ISSUE THREAD

**Issue by wiemax1093** [worktile/ngx-gantt#471]
Hey,

I#m jsut getting into this awesome project and encountered that in "hour" view the "today" line is off by a few hours.
Right now we have the 7th June 19:30, the line is set on the 8th June after 5am, see picture:
![grafik](https://github.com/worktile/ngx-gantt/assets/75943490/c72cf9db-9ccf-44c3-9a7d-3d0eb9ecd207)

I assume it is buggy or am I doing something wrong?
Thanks for any help

**Comment by wiemax1093** [comment]
Just found the other open issue (did not find it before opening mine), so seems to be still buggy? #452

**Comment by Fuasvak** [comment]
it's fix in code but no version seems to have been deploy since :/

**Comment by walkerkay** [comment]
Please upgrade to the latest version

**Comment by wiemax1093** [comment]
Just updated to 18.0.5 (18.1.0-next.0 has still the compile error in fsm2022 as reported in other issue) -
the "line" is now on the correct time, thx.
But also in 18.0.5 thehour view is not working accordingly. Now on 2nd March switching to GanttViewType.hour jumps to 3th of February and display data there from 1st of March onwards.

Firing the ...scrollToToday() event also jumps always to 3th of february. Can you have alook into that issue?

![Image](https://github.com/user-attachments/assets/7aba9460-4d65-4445-a672-bab9b71b9329)

![Image](https://github.com/user-attachments/assets/4e59e8cc-863d-4635-9896-ac7a8740cf27)
